import {Action} from './actionDispatcher'
import {DrinkType} from '../types/UserDrink'

export const updateRegistrationDetailsAction: Action<any> = 'updateRegistrationDetails'
export const createUserAction: Action<any> = 'createUser'
export const changePageAction: Action<string> = 'changePage'
export const addDrinkAction: Action<DrinkType> = 'addDrink'
export const drinkAction: Action<number> = 'drinkAction'
export const openDrinkAlertModalAction: Action<any> = 'openDrinkAlertModal'
export const closeDrinkAlertModalAction: Action<any> = 'closeDrinkAlertModal'
export const fetchMoreParticipantsAction: Action<any> = 'fetcMoreParticipants'
